development:
  adapter: postgresql
  encoding: unicode
  database: five_inch_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: five_inch_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: five_inch_production
  pool: 5

cucumber:
  <<: *test